# Generated by Django 4.2.7 on 2023-12-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=40)),
                ('photo', models.ImageField(max_length=255, upload_to='')),
                ('is_awarded', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=40)),
                ('photo', models.ImageField(max_length=255, upload_to='')),
                ('years_of_experience', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=25)),
                ('image', models.ImageField(max_length=250, upload_to='')),
                ('script', models.TextField(max_length=200)),
                ('release_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('actors', models.ManyToManyField(related_name='movies', to='imdb_app.actor')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='imdb_app.director')),
                ('protagonist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imdb_app.actor')),
            ],
        ),
    ]
