# Generated by Django 4.2.7 on 2023-12-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0002_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='title',
        ),
    ]
