# Generated by Django 4.2.7 on 2023-12-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0003_rename_movie_name_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
