# Generated by Django 4.2.7 on 2023-12-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0007_alter_movie_director_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='summary',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='director',
            name='summary',
            field=models.TextField(default='None'),
        ),
    ]
