# Generated by Django 4.2.7 on 2023-12-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0009_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Sci-Fi', 'Sci-Fi'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Mystery', 'Mystery')]),
        ),
    ]
