# Generated by Django 4.2.7 on 2023-12-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0012_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='director',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Sci-Fi', 'Sci-Fi'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
