# Generated by Django 4.2.7 on 2023-12-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0013_alter_actor_summary_alter_director_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
